[pytest]
markers =
    smoke: quick tests that check the API is alive
    regression: full detailed tests for all features
    negative: tests for bad or invalid inputs
    addopts = --clean-alluredir